import { FormElementDocnum } from "./types";

export const getFields = (): FormElementDocnum[] => {
  return [
    {
      checkFieldName: "chksaldocnum",
      textFieldName: "saldocnum",
      label: "Sales",
      placeholder: "Sales",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chksodocnum",
      textFieldName: "sodocnum",
      label: "Sales Order",
      placeholder: "Sales Order",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chksrtdocnum",
      textFieldName: "srtdocnum",
      label: "Sales Return",
      placeholder: "Sales Return",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkotdocnum",
      textFieldName: "otdocnum",
      label: "Other Receivables",
      placeholder: "Other Receivables",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkpodocnum",
      textFieldName: "podocnum",
      label: "Purchase Order",
      placeholder: "Purchase Order",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkaprdocnumfor",
      textFieldName: "aprdocnum",
      label: "Purchase Receiving",
      placeholder: "Purchase Receiving",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkarcdocnum",
      textFieldName: "arcdocnum",
      label: "Receipts Collection (Credit Memo)",
      placeholder: "Purchase Receiving",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkcashdocnum",
      textFieldName: "cashdocnum",
      label: "Cash Advances",
      placeholder: "Cash Advances",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkcusdocnum",
      textFieldName: "cusdocnum",
      label: "Customers",
      placeholder: "Customers",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkinvdocnum",
      textFieldName: "invdocnum",
      label: "Inventory",
      placeholder: "Inventory",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkgldocnum",
      textFieldName: "gldocnum",
      label: "Transaction GL Entry",
      placeholder: "Inventory",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkliqdocnum",
      textFieldName: "liqdocnum",
      label: "Liquidation",
      placeholder: "Liquidation",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkdeptdocnum",
      textFieldName: "deptdocnum",
      label: "Department",
      placeholder: "Department",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkitmcde",
      textFieldName: "itmcde",
      label: "Item",
      placeholder: "Item",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
    {
      checkFieldName: "chkitmclacde",
      textFieldName: "itmclacde",
      label: "Item Class",
      placeholder: "Item class",
      disabled: false,
      fullWidth: false,
      required: false,
      readOnly: false,
      autoFocus: true,
    },
  ];
};
